In [1]:
import numpy as np
import os

In [2]:
path = './middle/'    

In [3]:
datasets = ['ba','ws','TU_ENZYMES','TU_PROTEINS','Cora','CiteSeer']

In [4]:
tasks = ['Tfg-gcn_','Tfg-gat_','Tfg-idgcnfast_','Tfg-idgatfast_','Tfg-idgcn_','Tfg-idgat_']

In [5]:
def cal_mean_std(datasets,task,path):
    result = []
    acc_list = []
    for dataset in datasets:
        name = task + dataset + '.txt'
        acc = np.loadtxt(path+name)
        acc_list.append(acc)
    acc_max_list = []
    for acc in acc_list:
        acc_max_list.append(acc.max(1))   
    acc_max_np = np.array(acc_max_list)
    result.append(np.around(acc_max_np.mean(1),3))
    result.append(np.around(acc_max_np.std(1),2))
    return np.array(result)

In [6]:
results = []
for task in tasks:
    results.append(cal_mean_std(datasets,task,path))

In [7]:
results

[array([[0.695, 0.489, 0.54 , 0.481, 0.879, 0.763],
        [0.01 , 0.05 , 0.06 , 0.01 , 0.   , 0.01 ]]),
 array([[0.47 , 0.271, 0.492, 0.441, 0.878, 0.77 ],
        [0.03 , 0.03 , 0.07 , 0.02 , 0.   , 0.01 ]]),
 array([[0.764, 0.571, 0.724, 0.728, 0.88 , 0.756],
        [0.   , 0.05 , 0.05 , 0.01 , 0.01 , 0.01 ]]),
 array([[0.581, 0.616, 0.636, 0.621, 0.881, 0.759],
        [0.02 , 0.04 , 0.05 , 0.02 , 0.01 , 0.   ]]),
 array([[0.964, 0.994, 0.97 , 0.986, 0.787, 0.767],
        [0.01 , 0.   , 0.03 , 0.01 , 0.03 , 0.   ]]),
 array([[0.987, 0.967, 0.981, 0.991, 0.885, 0.771],
        [0.   , 0.04 , 0.02 , 0.   , 0.   , 0.01 ]])]

In [8]:
tasks = ['gnn-Tfg-idgin_','gnn-Tfg-idsage_']

In [9]:
results = []
for task in tasks:
    results.append(cal_mean_std(datasets,task,path))

In [10]:
results

[array([[0.66 , 0.503, 0.521, 0.54 , 1.   , 0.948],
        [0.03 , 0.05 , 0.09 , 0.01 , 0.   , 0.07 ]]),
 array([[0.579, 0.271, 0.608, 0.527, 1.   , 0.938],
        [0.07 , 0.03 , 0.07 , 0.01 , 0.   , 0.09 ]])]